---

nginx_real_ip: 127.0.0.1

nginx_papertrail_follow:
  - /var/log/drupal.log
  - /var/log/nginx/http-*error.log

apps:
  - server_name: www.test.com
    server_aliases: bob.com
    server_forwards: test.com
    http_port: 8080
    docroot: /var/www/test.com/current
  - server_name: test2.com
    server_aliases: www.example35.com www.example53.com
    http_port: 8080
    docroot: /var/www/test2.com/current

papertrail_enabled: False

# Default distribution CentOS 7
distro: "centos7"

nginx_conf:
  - client_header_timeout: 10
  - client_body_timeout: 120
  - send_timeout: 120
  - keepalive_timeout: "15 10"
  - client_max_body_size: 100M
  - client_body_buffer_size: 128k
  - proxy_read_timeout: 60


