---

# Setup New Relic repository

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm"
  when:
    distro == "rhel7" and newrelic_enabled == True

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm"
  when:
    distro == "centos7" and newrelic_enabled == True

# Install rewrelic

- yum:
    name={{ item }}
    state=present
  with_items:
    - newrelic-sysmond
  when:
    newrelic_enabled == True

- shell: "nrsysmond-config --set license_key={{ newrelic_license_key }}"
  when:
    newrelic_enabled == True


# Make sure all services are ON and configured to start on boot
- service: name={{ item }} state=started enabled=yes
  with_items:
    - newrelic-sysmond
  when:
    newrelic_enabled == True
